<?php

namespace App\Datas;

class SpecieList
{
    static $species = [
        ['name' => 'Bulbizarre', 'number' => '#001', 'typeIds' => [4, 8]],
        ['name' => 'Herbizarre', 'number' => '#002', 'typeIds' => [4, 8]],
        ['name' => 'Florizarre', 'number' => '#003', 'typeIds' => [4, 8]],
        ['name' => 'Salamèche', 'number' => '#004', 'typeIds' => [2]],
        ['name' => 'Reptincel', 'number' => '#005', 'typeIds' => [2]],
        ['name' => 'Dracaufeu', 'number' => '#006', 'typeIds' => [2, 16]],
        ['name' => 'Carapuce', 'number' => '#007', 'typeIds' => [3]],
        ['name' => 'Carabaffe', 'number' => '#008', 'typeIds' => [3]],
        ['name' => 'Tortank', 'number' => '#009', 'typeIds' => [3]],
        ['name' => 'Chenipan', 'number' => '#010', 'typeIds' => [12]],
        ['name' => 'Chrysacier', 'number' => '#011', 'typeIds' => [12]],
        ['name' => 'Papilusion', 'number' => '#012', 'typeIds' => [12, 10]],
        ['name' => 'Aspicot', 'number' => '#013', 'typeIds' => [12, 8]],
        ['name' => 'Coconfort', 'number' => '#014', 'typeIds' => [12, 8]],
        ['name' => 'Dardargnan', 'number' => '#015', 'typeIds' => [12, 8]],
        ['name' => 'Roucool', 'number' => '#016', 'typeIds' => [1, 10]],
        ['name' => 'Roucoups', 'number' => '#017', 'typeIds' => [1, 10]],
        ['name' => 'Roucarnage', 'number' => '#018', 'typeIds' => [1, 10]],
        ['name' => 'Rattata', 'number' => '#019', 'typeIds' => [1]],
        ['name' => 'Rattatac', 'number' => '#020', 'typeIds' => [1]],
        ['name' => 'Piafabec', 'number' => '#021', 'typeIds' => [1, 10]],
        ['name' => 'Rapasdepic', 'number' => '#022', 'typeIds' => [1, 10]],
        ['name' => 'Abo', 'number' => '#023', 'typeIds' => [8]],
        ['name' => 'Arbok', 'number' => '#024', 'typeIds' => [8]],
        ['name' => 'Pikachu', 'number' => '#025', 'typeIds' => [5]],
        ['name' => 'Raichu', 'number' => '#026', 'typeIds' => [5]],
        ['name' => 'Sabelette', 'number' => '#027', 'typeIds' => [9]],
        ['name' => 'Sablaireau', 'number' => '#028', 'typeIds' => [9]],
        ['name' => 'Nidoran♀', 'number' => '#029', 'typeIds' => [8]],
        ['name' => 'Nidorina', 'number' => '#030', 'typeIds' => [8]],
        ['name' => 'Nidoqueen', 'number' => '#031', 'typeIds' => [8, 9]],
        ['name' => 'Nidoran♂', 'number' => '#032', 'typeIds' => [8]],
        ['name' => 'Nidorino', 'number' => '#033', 'typeIds' => [8]],
        ['name' => 'Nidoking', 'number' => '#034', 'typeIds' => [8, 9]],
        ['name' => 'Mélofée', 'number' => '#035', 'typeIds' => [1]],
        ['name' => 'Mélodelfe', 'number' => '#036', 'typeIds' => [1]],
        ['name' => 'Goupix', 'number' => '#037', 'typeIds' => [2]],
        ['name' => 'Feunard', 'number' => '#038', 'typeIds' => [2]],
        ['name' => 'Rondoudou', 'number' => '#039', 'typeIds' => [1]],
        ['name' => 'Grodoudou', 'number' => '#040', 'typeIds' => [1]],
        ['name' => 'Nosferapti', 'number' => '#041', 'typeIds' => [8,10]],
        ['name' => 'Nosferalto', 'number' => '#042', 'typeIds' => [8,10]],
        ['name' => 'Mystherbe', 'number' => '#043', 'typeIds' => [4, 8]],
        ['name' => 'Ortide', 'number' => '#044', 'typeIds' => [4, 8]],
        ['name' => 'Rafflesia', 'number' => '#045', 'typeIds' => [4, 8]],
        ['name' => 'Paras', 'number' => '#046', 'typeIds' => [4, 12]],
        ['name' => 'Parasect', 'number' => '#047', 'typeIds' => [4, 12]],
        ['name' => 'Mimitoss', 'number' => '#048', 'typeIds' => [8, 12]],
        ['name' => 'Aéromite', 'number' => '#049', 'typeIds' => [8, 12]],
        ['name' => 'Taupiqueur', 'number' => '#050', 'typeIds' => [9]],
        ['name' => 'Triopikeur', 'number' => '#051', 'typeIds' => [9]],
        ['name' => 'Miaouss', 'number' => '#052', 'typeIds' => [1]],
        ['name' => 'Persian', 'number' => '#053', 'typeIds' => [1]],
        ['name' => 'Psykokwak', 'number' => '#054', 'typeIds' => [3]],
        ['name' => 'Akwakwak', 'number' => '#055', 'typeIds' => [3]],
        ['name' => 'Férosinge', 'number' => '#056', 'typeIds' => [7]],
        ['name' => 'Colossinge', 'number' => '#057', 'typeIds' => [7]],
        ['name' => 'Caninos', 'number' => '#058', 'typeIds' => [2]],
        ['name' => 'Arcanin', 'number' => '#059', 'typeIds' => [2]],
        ['name' => 'Ptitard', 'number' => '#060', 'typeIds' => [3]],
        ['name' => 'Têtarte', 'number' => '#061', 'typeIds' => [3]],
        ['name' => 'Tartard', 'number' => '#062', 'typeIds' => [3,7]],
        ['name' => 'Abra', 'number' => '#063', 'typeIds' => [11]],
        ['name' => 'Kadabra', 'number' => '#064', 'typeIds' => [11]],
        ['name' => 'Alakazam', 'number' => '#065', 'typeIds' => [11]],
        ['name' => 'Machoc', 'number' => '#066', 'typeIds' => [7]],
        ['name' => 'Machopeur', 'number' => '#067', 'typeIds' => [7]],
        ['name' => 'Mackogneur', 'number' => '#068', 'typeIds' => [7]],
        ['name' => 'Chétiflor', 'number' => '#069', 'typeIds' => [4,8]],
        ['name' => 'Boustiflor', 'number' => '#070', 'typeIds' => [4,8]],
        ['name' => 'Empiflor', 'number' => '#071', 'typeIds' => [4,8]],
        ['name' => 'Tentacool', 'number' => '#072', 'typeIds' => [3,8]],
        ['name' => 'Tentacruel', 'number' => '#073', 'typeIds' => [3,8]],
        ['name' => 'Racaillou', 'number' => '#074', 'typeIds' => [9,13]],
        ['name' => 'Gravalanch', 'number' => '#075', 'typeIds' => [9,13]],
        ['name' => 'Grolem', 'number' => '#076', 'typeIds' => [9,13]],
        ['name' => 'Ponyta', 'number' => '#077', 'typeIds' => [2]],
        ['name' => 'Galopa', 'number' => '#078', 'typeIds' => [2]],
        ['name' => 'Ramoloss', 'number' => '#079', 'typeIds' => [3,11]],
        ['name' => 'Flagadoss', 'number' => '#080', 'typeIds' => [3,11]],
        ['name' => 'Magnéti', 'number' => '#081', 'typeIds' => [5]],
        ['name' => 'Magnéton', 'number' => '#082', 'typeIds' => [5]],
        ['name' => 'Canarticho', 'number' => '#083', 'typeIds' => [1,10]],
        ['name' => 'Doduo', 'number' => '#084', 'typeIds' => [1,10]],
        ['name' => 'Dodrio', 'number' => '#085', 'typeIds' => [1,10]],
        ['name' => 'Otaria', 'number' => '#086', 'typeIds' => [3]],
        ['name' => 'Lamantine', 'number' => '#087', 'typeIds' => [3,6]],
        ['name' => 'Tadmorv', 'number' => '#088', 'typeIds' => [8]],
        ['name' => 'Grotadmorv', 'number' => '#089', 'typeIds' => [8]],
        ['name' => 'Kokiyas', 'number' => '#090', 'typeIds' => [3]],
        ['name' => 'Crustabri', 'number' => '#091', 'typeIds' => [3,6]],
        ['name' => 'Fantominus', 'number' => '#092', 'typeIds' => [8,14]],
        ['name' => 'Spectrum', 'number' => '#093', 'typeIds' => [8,14]],
        ['name' => 'Ectoplasma', 'number' => '#094', 'typeIds' => [8,14]],
        ['name' => 'Onix', 'number' => '#095', 'typeIds' => [9,13]],
        ['name' => 'Soporifik', 'number' => '#096', 'typeIds' => [11]],
        ['name' => 'Hypnomade', 'number' => '#097', 'typeIds' => [11]],
        ['name' => 'Krabby', 'number' => '#098', 'typeIds' => [3]],
        ['name' => 'Krabboss', 'number' => '#099', 'typeIds' => [3]],
        ['name' => 'Voltorbe', 'number' => '#100', 'typeIds' => [5]],
        ['name' => 'Electrode', 'number' => '#101', 'typeIds' => [5]],
        ['name' => 'Noeunoeuf', 'number' => '#102', 'typeIds' => [4,11]],
        ['name' => 'Noadkoko', 'number' => '#103', 'typeIds' => [4,11]],
        ['name' => 'Osselait', 'number' => '#104', 'typeIds' => [9]],
        ['name' => 'Ossatueur', 'number' => '#105', 'typeIds' => [9]],
        ['name' => 'Kicklee', 'number' => '#106', 'typeIds' => [7]],
        ['name' => 'Tygnon', 'number' => '#107', 'typeIds' => [7]],
        ['name' => 'Excelangue', 'number' => '#108', 'typeIds' => [1]],
        ['name' => 'Smogo', 'number' => '#109', 'typeIds' => [8]],
        ['name' => 'Smogogo', 'number' => '#110', 'typeIds' => [8]],
        ['name' => 'Rhinocorne', 'number' => '#111', 'typeIds' => [9,13]],
        ['name' => 'Rhinoféros', 'number' => '#112', 'typeIds' => [9,13]],
        ['name' => 'Leveinard', 'number' => '#113', 'typeIds' => [1]],
        ['name' => 'Saquedeneu', 'number' => '#114', 'typeIds' => [4]],
        ['name' => 'Kangourex', 'number' => '#115', 'typeIds' => [1]],
        ['name' => 'Hypotrempe', 'number' => '#116', 'typeIds' => [3]],
        ['name' => 'Hypocéan', 'number' => '#117', 'typeIds' => [3]],
        ['name' => 'Poissirène', 'number' => '#118', 'typeIds' => [3]],
        ['name' => 'Poissoroy', 'number' => '#119', 'typeIds' => [3]],
        ['name' => 'Stari', 'number' => '#120', 'typeIds' => [3]],
        ['name' => 'Staross', 'number' => '#121', 'typeIds' => [3,11]],
        ['name' => 'M. Mime', 'number' => '#122', 'typeIds' => [11]],
        ['name' => 'Insécateur', 'number' => '#123', 'typeIds' => [10,12]],
        ['name' => 'Lippoutou', 'number' => '#124', 'typeIds' => [6,11]],
        ['name' => 'Elektek', 'number' => '#125', 'typeIds' => [5]],
        ['name' => 'Magmar', 'number' => '#126', 'typeIds' => [2]],
        ['name' => 'Scarabrute', 'number' => '#127', 'typeIds' => [12]],
        ['name' => 'Tauros', 'number' => '#128', 'typeIds' => [1]],
        ['name' => 'Magicarpe', 'number' => '#129', 'typeIds' => [3]],
        ['name' => 'Léviator', 'number' => '#130','typeIds' => [3,10]],
        ['name' => 'Lokhlass', 'number' => '#131', 'typeIds' => [3,6]],
        ['name' => 'Métamorph', 'number' => '#132', 'typeIds' => [1]],
        ['name' => 'Evoli', 'number' => '#133', 'typeIds' => [1]],
        ['name' => 'Aquali', 'number' => '#134', 'typeIds' => [3]],
        ['name' => 'Voltali', 'number' => '#135', 'typeIds' => [5]],
        ['name' => 'Pyroli', 'number' => '#136', 'typeIds' => [2]],
        ['name' => 'Porygon', 'number' => '#137', 'typeIds' => [1]],
        ['name' => 'Amonita', 'number' => '#138', 'typeIds' => [3,13]],
        ['name' => 'Amonistar', 'number' => '#139', 'typeIds' => [3,13]],
        ['name' => 'Kabuto', 'number' => '#140', 'typeIds' => [3,13]],
        ['name' => 'Kabutops', 'number' => '#141', 'typeIds' => [3,13]],
        ['name' => 'Ptéra', 'number' => '#142', 'typeIds' => [10,13]],
        ['name' => 'Ronflex', 'number' => '#143', 'typeIds' => [1]],
        ['name' => 'Artikodin', 'number' => '#144', 'typeIds' => [6,10]],
        ['name' => 'Électhor', 'number' => '#145', 'typeIds' => [5,10]],
        ['name' => 'Sulfura', 'number' => '#146', 'typeIds' => [2,10]],
        ['name' => 'Minidraco', 'number' => '#147', 'typeIds' => [15]],
        ['name' => 'Draco', 'number' => '#148', 'typeIds' => [15]],
        ['name' => 'Dracolosse', 'number' => '#149', 'typeIds' => [10,15]],
        ['name' => 'Mewtwo', 'number' => '#150', 'typeIds' => [11]],
        ['name' => 'Mew', 'number' => '#151', 'typeIds' => [11]],
    ];
}